apiVersion: v1
kind: ServiceAccount
metadata:
  name: algorithm-runtime
  namespace: panoptes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: panoptes
  name: job-creator
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-jobs
  namespace: panoptes
subjects:
- kind: ServiceAccount
  name: algorithm-runtime
  namespace: panoptes
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io